basic.showIcon(IconNames.Silly)
basic.pause(1000)
basic.showIcon(IconNames.Yes)
basic.pause(1000)
basic.forever(function () {
    serial.writeLine("Temperature")
    serial.writeLine("" + (input.temperature()))
    serial.writeLine("")
    serial.writeLine("Intensite lumineuse")
    serial.writeLine("" + (input.lightLevel()))
    serial.writeLine("")
    serial.writeLine("Champ magnetique")
    serial.writeLine("" + (input.magneticForce(Dimension.X)))
    serial.writeLine("")
    basic.pause(1000)
})
